# Generated by Django 4.2.10 on 2024-04-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_remove_plan_workouts'),
        ('profiles', '0002_planworkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='paid_plans',
            field=models.ManyToManyField(blank=True, related_name='profile_plans', to='workouts.plan'),
        ),
    ]
