# Generated by Django 4.2.10 on 2024-04-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts_in_plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='plan',
        ),
    ]
