# Generated by Django 4.2.10 on 2024-04-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts_in_plan', '0002_remove_workout_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
