# Generated by Django 4.2.10 on 2024-04-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts_in_plan', '0003_workout_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='video_url',
        ),
    ]
