# Generated by Django 4.2.10 on 2024-04-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts_in_plan', '0002_remove_workout_plan'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='workouts',
            field=models.ManyToManyField(to='workouts_in_plan.workout'),
        ),
    ]
