# Generated by Django 4.2.10 on 2024-04-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts_in_plan', '0002_remove_workout_plan'),
        ('workouts', '0002_plan_workouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='workouts',
            field=models.ManyToManyField(blank=True, null=True, to='workouts_in_plan.workout'),
        ),
    ]
