# Generated by Django 4.2.10 on 2024-04-08 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts_in_plan', '0003_workout_video_url'),
        ('workouts', '0003_alter_plan_workouts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='workouts',
        ),
        migrations.AddField(
            model_name='plan',
            name='workouts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts_in_plan.workout'),
        ),
    ]
