# Generated by Django 4.2.10 on 2024-04-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_remove_plan_workouts_plan_workouts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='workouts',
        ),
    ]
